# Generated by Django 3.2.1 on 2022-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backends", "0002_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="description",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backend",
            name="num_wires",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
