# Generated by Django 3.2.1 on 2022-01-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backends", "0003_auto_20220110_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
